<h1>Tutorial Algebra Lineal</h1>
<h2>Resumen</h2>
En el siguiente tutorial se desarrollara una pequeña implementacion que ayude al aprendiz a obtener una serie de ayudas para desarrollar operaciones de algebra lineal para vectores y matrices en <b>Python</b>, dichas operaciones se lograran gracias a la ayuda de <i><b>numpy</b></i> con una de sus sublibrerias denominada <i><b>linalg</b> "<b>lin</b>ear <b>alg</b>ebra"</i>

Inicialmente cargamos las librerias que usaremos, procedemos a cargar <b>numpy</b> y <b>numpy.linalg</b> respectivamente con la abreviacion que se usara dentro del codigo.

In [1]:
import numpy as np
import numpy.linalg as la

Posteriormente a importar las librerias a usar, debemos declarar variables con las que vamos a trabajar, en nuestro caso sera suficiente generar 2 vectores de 5 elementos y 2 matrices de 5x5.

In [2]:
a=np.arange(0,5)
b=np.arange(5,10)
ma=np.arange(25).reshape(5,5)
mb=np.arange(25,50).reshape(5,5)
print(a)
print(b)
print(ma)
print(mb)

[0 1 2 3 4]
[5 6 7 8 9]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
