# Tutorial Algebra Lineal
## Autores

|Nombre|Codigo|correo
|---|---|
| David Felipe Peña Huertas | 20132020018 | dfpenah@correo.udistrital.edu.co |
| Anthony Jason Vargas Sepulveda | 20132020115 | ajvargass@corre.udistrital.edu.co|
## Resumen
En el siguiente tutorial se desarrollara una pequeña implementacion que ayude al aprendiz a obtener una serie de ayudas para desarrollar operaciones de algebra lineal para vectores y matrices en **Python**, dichas operaciones se lograran gracias a la ayuda de ***numpy*** con una de sus sublibrerias denominada ***linalg*** "_**lin**ear **alg**ebra_"

Inicialmente cargamos las librerias que usaremos, procedemos a cargar **numpy** y **numpy.linalg** respectivamente con la abreviacion que se usara dentro del codigo.

In [1]:
import numpy as np
from numpy import linalg as la

Posteriormente a importar las librerias a usar, debemos declarar variables con las que vamos a trabajar, en nuestro caso sera suficiente generar 2 vectores de 5 elementos y 2 matrices de 5x5.

In [2]:
a=np.arange(0,5)
b=np.arange(5,10)
ma=np.arange(25).reshape(5,5)
mb=np.arange(25,50).reshape(5,5)

### Propiedades de matrices
Algunas de las propiedades mas basicas de las matrices son fundamentales al realizar operaciones en el algebra lineal fundamental, a continuacion presentaremos con algunos de los ejemplos las propiedades elementales realizadas mediante la libreria linalg.
* Matriz inversa
* Determinante de la matriz
* Logaritmo del determinante de una matriz con signo
* Numero condicional de la matriz
* Traza de la matriz cuadrada
* Eigen valores

In [3]:
#Retorna la matriz inversa de un matriz cuadrada
la.inv(mb)

array([[-5.37805787e+13,  1.36896018e+14, -1.13148750e+14,
         3.07317592e+13, -6.98449074e+11],
       [-2.27694398e+14, -1.36896018e+14,  6.76098703e+14,
        -3.07317592e+13, -2.80776528e+14],
       [ 3.42938495e+14, -1.56452593e+14, -5.14058518e+14,
         1.25720833e+14,  2.01851782e+14],
       [ 2.12328518e+14,  1.76009167e+14, -5.47584074e+14,
        -2.82173426e+14,  4.41419815e+14],
       [-2.73792037e+14, -1.95565741e+13,  4.98692639e+14,
         1.56452593e+14, -3.61796620e+14]])

In [4]:
#Retorna el determinante de una matriz cuadrada
la.det(mb)

1.6134950889225737e-42

In [5]:
#Retorna el signo de logaritmo natural del determinante y el valor del logaritmo natural del determinante
la.slogdet(mb)

(1.0, -96.23017121698649)

In [6]:
#Retorna el numero de condicion, dependiendo del parametro de normalizacion que se le pase a la funcion 
#(ninguno, 'fro', inf, -inf, 1, -1, 2, -2)
la.cond(mb,-2)

9.00576794385169e-18

In [7]:
#Retorna la traza de la matriz, la cual es la sumatoria de los elementos de la diagonal principal
np.trace(ma)

60

In [8]:
#Retorna los eigen valores de la matriz cuadrada
la.eigvals(mb)

array([ 1.86341622e+02+0.00000000e+00j, -1.34162190e+00+0.00000000e+00j,
        1.26094357e-15+0.00000000e+00j, -1.25838784e-15+2.56683375e-15j,
       -1.25838784e-15-2.56683375e-15j])

### Operaciones con matrices
En los siguientes ejemplo se presentaran algunas de las operaciones entre matrices que se puede realizar mediante la libreria _linalg_ a continuación se muestran algunos ejemplos de operaciones mas comunes con matrices.
* Producto punto de una matriz
* Multiplicacion de cada uno de los elementos entre matrices
* Resolver un sistema de ecuaciones lineal
* Multiplicativo de matrices
* Producto Kroniano

In [9]:
#Multiplica un elemento para cada uno de los elementos de la matriz/el vector
display(np.dot(5,ma))
display(np.dot(4,a))

array([[  0,   5,  10,  15,  20],
       [ 25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70],
       [ 75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120]])

array([ 0,  4,  8, 12, 16])

In [10]:
#Retorna cada uno de los elementos de la matriz a con cada uno de la matriz b ya sea con matrizes o vectores
np.outer(a,b)

array([[ 0,  0,  0,  0,  0],
       [ 5,  6,  7,  8,  9],
       [10, 12, 14, 16, 18],
       [15, 18, 21, 24, 27],
       [20, 24, 28, 32, 36]])

In [11]:
#Resuelve los resultados de un sistema de ecuaciones lineal
la.solve([[1,3],[3,2]],[8,1])

array([-1.85714286,  3.28571429])

In [12]:
#Retorna el multiplicativo de dos matrices o vectores
np.matmul(ma,mb)

array([[ 400,  410,  420,  430,  440],
       [1275, 1310, 1345, 1380, 1415],
       [2150, 2210, 2270, 2330, 2390],
       [3025, 3110, 3195, 3280, 3365],
       [3900, 4010, 4120, 4230, 4340]])

In [13]:
#Retorna el producto kroniano entre dos vectores/matrices
np.kron(a,b)

array([ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10, 12, 14, 16, 18, 15, 18,
       21, 24, 27, 20, 24, 28, 32, 36])